# Generated by Django 5.2.4 on 2025-11-14 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_module_chatsession_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(blank=True, help_text='Specific topic this chat session is for', max_length=200),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'module', 'topic'], name='learning_ch_user_id_4b150e_idx'),
        ),
    ]
