# Generated by Django 5.2.4 on 2025-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_quiz_quizquestion_quizoption_userquizattempt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="course",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Display order in course list (lower numbers appear first)",
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[("multiple_choice", "Multiple Choice (MCQ)")],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
