# Generated by Django 5.2.4 on 2025-12-02 04:08

from django.db import migrations


def set_initial_course_order(apps, schema_editor):
    """Set initial order values for existing courses based on creation date"""
    Course = apps.get_model('learning', 'Course')
    courses = Course.objects.all().order_by('created_at')
    for index, course in enumerate(courses, start=1):
        course.order = index
        course.save(update_fields=['order'])


def reverse_set_initial_course_order(apps, schema_editor):
    """Reverse migration - set all orders back to 1"""
    Course = apps.get_model('learning', 'Course')
    Course.objects.all().update(order=1)


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_alter_course_options_course_order_and_more"),
    ]

    operations = [
        migrations.RunPython(set_initial_course_order, reverse_set_initial_course_order),
    ]
