# Generated by Django 5.2.4 on 2025-12-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_enrollmentrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquizattempt",
            name="auto_submitted",
            field=models.BooleanField(
                default=False,
                help_text="Whether quiz was auto-submitted due to violations",
            ),
        ),
        migrations.AddField(
            model_name="userquizattempt",
            name="violation_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of violations detected"
            ),
        ),
        migrations.AddField(
            model_name="userquizattempt",
            name="violation_details",
            field=models.TextField(
                blank=True,
                help_text="Details of violations (tab switches, copy/paste, etc.)",
            ),
        ),
    ]
