# Generated by Django 5.2.4 on 2025-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0011_add_quiz_attempt_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattemptrequest",
            name="used",
            field=models.BooleanField(
                default=False,
                help_text="Whether the approved request has been used for an attempt",
            ),
        ),
    ]
