# Generated by Django 5.2.4 on 2025-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0012_add_used_field_to_quiz_attempt_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Tell us about yourself and your learning journey",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="Optional: Your GitHub username", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="interests",
            field=models.TextField(
                blank=True,
                help_text="Your interests (e.g., Web Development, Data Science, AI)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="learning_goals",
            field=models.TextField(
                blank=True, help_text="What do you want to achieve?", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="Optional: Your LinkedIn profile URL"
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Optional: Your location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Optional: Your contact number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="preferred_languages",
            field=models.CharField(
                blank=True,
                help_text="Preferred programming languages (comma-separated)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="skill_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                help_text="Your current skill level",
                max_length=20,
            ),
        ),
    ]
