# Generated by Django 5.2.4 on 2025-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0013_add_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Your profile picture",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
